const express = require('express');
const router = express.Router();
const { registerUser, loginUser, verificationEmail, verifyCode, getUserProfile, getUserProfileThread, addNewThread, getAllCommentOfThread, addNewComment, updateUserProfile, get10LastedActivity, checkUserCookie, logoutUser, getAllCategoryAndTopic, getTopicAndAllThread, getThreadAndAllComment, getNotifications, markNotificationAsRead, markAllNotificationsAsRead, changePassword, getAboutPage, getPrivacyPage, getTermsPage, getHelpPage, search, uploadAvatar, uploadMiddleware, getAllTopics, getAllTags, makeNewThread, uploadFile, getUserAvatar, checkUsernameAvailability, getThreadAttachments, downloadAttachment, chat, getUserById, getAllThreadByUserID, get5MostThreadTag, getAllClubs, getClubByID, createClub, updateClub, deleteClub, getClubsByPresident } = require('../controllers/homeController');

router.post('/register', registerUser);
router.post('/login', loginUser);
router.post('/verification', verificationEmail);
router.post('/verify-code', verifyCode);
router.post('/getUserProfile', getUserProfile);
router.get('/getUserProfileThread', getUserProfileThread);
router.post('/addNewThread', addNewThread);
router.get('/getAllCommentOfThread', getAllCommentOfThread);
router.post('/addNewComment', addNewComment);
router.post('/updateUserProfile', updateUserProfile);
router.get('/get10LastedActivity', get10LastedActivity);
router.get('/check-cookie', checkUserCookie);
router.post('/logout', logoutUser);
router.get('/getAllCategoryAndTopic', getAllCategoryAndTopic);
router.get('/getTopicAndAllThread', getTopicAndAllThread);
router.get('/getThreadAndAllComment', getThreadAndAllComment);
router.post('/getNotifications', getNotifications);
router.post('/markNotificationAsRead', markNotificationAsRead);
router.post('/markAllNotificationsAsRead', markAllNotificationsAsRead);
router.post('/changePassword', changePassword);
router.get('/about', getAboutPage);
router.get('/privacy', getPrivacyPage);
router.get('/terms', getTermsPage);
router.get('/help', getHelpPage);
router.get('/search', search);
router.post("/uploadAvatar", uploadMiddleware, uploadAvatar);
router.get("/topics", getAllTopics);
router.get("/tags", getAllTags);
router.post('/threads', uploadFile, makeNewThread);
router.get("/getUserAvatar", getUserAvatar);
router.get('/check-username/:username', checkUsernameAvailability);
router.get('/thread/:threadId/attachments', getThreadAttachments);
router.get('/download/:fileId', downloadAttachment);
router.post('/chatbot', chat);
router.get('/user/:id', getUserById);
router.get('/getAllThread', getAllThreadByUserID);
router.get('/5MostThreadTag', get5MostThreadTag);

// Club routes
router.get('/clubs', getAllClubs);
router.get('/clubs/:id', getClubByID);
router.post('/clubs', createClub);
router.put('/clubs', updateClub);
router.delete('/clubs/:id', deleteClub);
router.get('/clubs/president/:presidentID', getClubsByPresident);

module.exports = router;