const express = require('express');
const router = express.Router();
const { registerUser, loginUser, verificationEmail, verifyCode, getUserProfile, getUserProfileThread, addNewThread, getAllCommentOfThread, addNewComment, updateUserProfile, get10LastedActivity, checkUserCookie, logoutUser, getAllCategoryAndTopic, getTopicAndAllThread, getThreadAndAllComment, getNotifications, markNotificationAsRead, markAllNotificationsAsRead } = require('../controllers/homeController');

router.post('/register', registerUser);
router.post('/login', loginUser);
router.post('/verification', verificationEmail);
router.post('/verify-code', verifyCode);
router.post('/getUserProfile', getUserProfile);
router.get('/getUserProfileThread', getUserProfileThread);
router.post('/addNewThread', addNewThread);
router.get('/getAllCommentOfThread', getAllCommentOfThread);
router.post('/addNewComment', addNewComment);
router.post('/updateUserProfile', updateUserProfile);
router.get('/get10LastedActivity', get10LastedActivity);
router.get('/check-cookie', checkUserCookie);
router.post('/logout', logoutUser);
router.get('/getAllCategoryAndTopic', getAllCategoryAndTopic);
router.get('/getTopicAndAllThread', getTopicAndAllThread);
router.get('/getThreadAndAllComment', getThreadAndAllComment);
router.post('/getNotifications', getNotifications);
router.post('/markNotificationAsRead', markNotificationAsRead);
router.post('/markAllNotificationsAsRead', markAllNotificationsAsRead);
module.exports = router;